.gitignore
.storybook/addons.js
.storybook/webpack.config.js
package-lock.json
package.json
yarn.lock

This adds the Storysource addon to Storybook as requested in #9 
I wasn't sure if I should use yarn or npm because both lockfiles existed so I updated both lockfiles. (see also #18) Not sure why there are so large differences in both lockfiles though.
Let me know if this works for you.
Screenshot:

add storysource addon

---

.storybook/webpack.config.js
package-lock.json
package.json

Storybook is now on the latest version.
(These package-lock diffs are crazy 😲)
closes #20

update storybook to v5

---

README.md

Use single quotes in README example

---

package-lock.json
src/components/Window/Window.stories.js

Not sure if appropriate, but will a button in a header work to address issue #15 
I don't really think it needs some special prop. You can attach actions to it like a standard button.

Add a storybook example for Window with close.

---

src/components/Button/Button.stories.js

demonstrates all available button sizes in Storybook

Christoshrousis button sizes

---

.eslintrc.js
.prettierrc
package-lock.json
package.json

Just adding `prettier` to the project :)
_This closes #54._

Add and configure prettier with pre-commit hook

---

src/components/Checkbox/Checkbox.js
src/components/Radio/Radio.js
src/components/TextArea/TextArea.js
src/components/TextField/TextField.js

Passing refs to input components

---

src/components/Checkbox/Checkbox.stories.js
src/components/SwitchBase/SwitchBase.js
src/components/TextField/TextField.js
src/components/WindowHeader/WindowHeader.js
src/components/common/index.js
src/components/common/themes.js

BREAKING CHANGE: WindowHeader related theme variables changed

feat(themes): add themes

---

src/components/Slider/Slider.js
src/components/Slider/Slider.spec.js
src/components/Slider/Slider.stories.js

fix(slider): fix Slider origin and decimal issues

---

src/components/Button/Button.spec.js
src/components/Checkbox/Checkbox.js
src/components/ColorInput/ColorInput.js
src/components/DatePicker/DatePicker.js
src/components/Fieldset/Fieldset.js
src/components/Fieldset/Fieldset.spec.js
src/components/ListItem/ListItem.js
src/components/ListItem/ListItem.spec.js
src/components/NumberField/NumberField.js
src/components/Progress/Progress.js
src/components/Radio/Radio.js
src/components/Radio/Radio.stories.js
src/components/Select/Select.styles.js
src/components/Slider/Slider.js
src/components/SwitchBase/SwitchBase.js
src/components/Tab/Tab.js
src/components/TableHeadCell/TableHeadCell.js
src/components/TableRow/TableRow.js
src/components/TextField/TextField.js
src/components/Window/Window.stories.js
src/components/common/index.js
src/components/common/themes.js

'text' remamed to 'materialText', 'inputText' renamed to 'canvasText'
BREAKING CHANGE: 'text' remamed to 'materialText', 'inputText' renamed to 'canvasText'

fix(themes): rename text related color variables

---

src/Slider/Slider.js
src/Slider/Slider.stories.js

fix(slider): fix tick values alignment

---

src/Counter/Counter.js
src/Counter/Counter.mdx
src/Counter/Counter.spec.js
src/Counter/Counter.stories.js
src/Counter/Digit.js
src/common/index.js
src/index.js

feat(counter): add Counter component

---

src/Tab/Tab.js
src/Tabs/Tabs.js
src/Tabs/Tabs.spec.js
src/Tabs/Tabs.stories.js

adds support for multi row tabs
#206

feat(tabs): add support for multi row tabs

---

src/common/themes/aiee.js
src/common/themes/ash.js
src/common/themes/blue.js
src/common/themes/cherry.js
src/common/themes/darkTeal.js
src/common/themes/fxDev.js
src/common/themes/hotChocolate.js
src/common/themes/index.js
src/common/themes/peggysPastels.js
src/common/themes/polarized.js
src/common/themes/powerShell.js
src/common/themes/raspberry.js
src/common/themes/redWine.js
src/common/themes/seawater.js
src/common/themes/solarizedDark.js
src/common/themes/solarizedLight.js
src/common/themes/stormClouds.js
src/common/themes/wmii.js

Issue: #213
Themes added: 
aiee
ash
blue
cherry
darkTeal
fxDev
hotChocolate
monochrome
polarized
powerShell
raspberry
redWine
seawater
solarizedDark
solarizedLight
stormClouds
wmii

feat(themes): add more themes by tPenguinLTG

---

src/common/themes/denim.js
src/common/themes/honey.js
src/common/themes/hotdogStand.js
src/common/themes/index.js
src/common/themes/shelbiTeal.js
src/common/themes/toner.js
src/common/themes/vistaesqueMidnight.js
src/common/themes/white.js
src/common/themes/windows1.js

Add the following themes that were left out from #224:
- denim
- honey
- hotdogStand
- shelbiTeal
- toner
- vistaesqueMidnight
- white
- windows1
Closes #213

feat(themes): add 8 more themes by tPenguinLTG

---

package-lock.json
src/List/List.stories.js
src/ListItem/ListItem.js
src/ListItem/ListItem.mdx

This PR partially implements #216. This adds the `Primary` prop to ListItem. 
FYI @arturbien

feat: add primary prop to ListItem

---

src/Tooltip/Tooltip.js

change the direction to 'up', 'down', 'left', 'right'

added direction prop to the tooltip component

---

src/Counter/Digit.js
src/SwitchBase/SwitchBase.js
src/Tree/Tree.js
src/Tree/Tree.spec.js
src/Tree/Tree.stories.js
src/index.js

Resolves https://github.com/arturbien/React95/issues/209 (add Tree component)

Implement Tree component

---

src/Anchor/Anchor.tsx
tsconfig.json

This also includes:
- chore(types): remove baseUrl from tsconfig.json
That causes import path issues on VSCode.

chore(anchor): fix import path

---

.eslintrc.js
src/Checkbox/Checkbox.mdx
src/Checkbox/Checkbox.spec.tsx
src/Checkbox/Checkbox.stories.tsx
src/Checkbox/Checkbox.tsx
src/SwitchBase/SwitchBase.ts
src/common/index.ts
src/index.ts
src/types.tsx

This also includes:
- chore(switchbase): convert to TypeScript and export types
- feat(common): add withoutForwardingProps styled helper
- chore(lint): disable no-undef on TypeScript files

feat(checkbox): convert to TypeScript and export types

---

src/LoadingIndicator/LoadingIndicator.spec.tsx
src/LoadingIndicator/LoadingIndicator.stories.tsx
src/LoadingIndicator/LoadingIndicator.tsx
src/index.ts

feat(loadingindicator): convert to TypeScript and export types

---

src/Button/Button.stories.tsx
src/Button/Button.tsx
src/Checkbox/Checkbox.tsx
src/Fieldset/Fieldset.stories.tsx
src/List/List.stories.tsx
src/ListItem/ListItem.tsx
src/Radio/Radio.stories.tsx
src/Radio/Radio.tsx
src/Select/Select.spec.tsx
src/Select/Select.stories.tsx
src/Select/Select.tsx
src/Select/Select.types.ts
src/Tabs/Tabs.stories.tsx

Including:
- Omitting default React props that we are redefining
- Making Select value type generic
- Etc.

fix(types): fix multiple TypeScript issues

---

.github/workflows/ci.yml
package.json
src/Checkbox/Checkbox.tsx

This also fixes some remaining lint issues.

ci: add lint and type checking

---

src/Frame/Frame.tsx

Note: this commit includes changes from #332, given that was opened in a fork. It should be rebased once that is merged.

refactor(frame): update variants to align with guideline

---

src/Slider/Slider.stories.tsx
src/Slider/Slider.tsx
src/common/hooks/useEventCallback.ts

fix(slider): fix thumb not draggable
